.TH "hub-ci-status" "1" "05 Mar 2020" "hub version 2.14.2" "hub manual"
.nh
.ad l
.SH "NAME"
hub\-ci\-status \- Display status of GitHub checks for a commit.
.SH "SYNOPSIS"
.P
\fB\fChub ci\-status\fR [\-v] [\fICOMMIT\fP]
.SH "OPTIONS"
.PP
\-v, \-\-verbose
.RS 4
Print detailed report of all status checks and their URLs.
.RE
.PP
\-f, \-\-format \fIFORMAT\fP
.RS 4
Pretty print all status checks using \fIFORMAT\fP (implies \fB\fC\-\-verbose\fR). See the
"PRETTY FORMATS" section of git\-log(1) for some additional details on how
placeholders are used in format. The available placeholders for checks are:
.sp
%U: the URL of this status check
.sp
%S: check state (e.g. "success", "failure")
.sp
%sC: set color to red, green, or yellow, depending on state
.sp
%t: name of the status check
.RE
.PP
\-\-color[=\fIWHEN\fP]
.RS 4
Enable colored output even if stdout is not a terminal. \fIWHEN\fP can be one
of "always" (default for \fB\fC\-\-color\fR), "never", or "auto" (default).
.RE
.PP
\fICOMMIT\fP
.RS 4
A commit SHA or branch name (default: "HEAD").
.RE
.br
.P
Possible outputs and exit statuses:
.IP \(bu 2.3
success, neutral: 0
.sp -1
.IP \(bu 2.3
failure, error, action\_required, cancelled, timed\_out: 1
.sp -1
.IP \(bu 2.3
pending: 2
.br
.SH "SEE ALSO"
.P
hub\-pull\-request(1), hub(1)

