.TH "hub-create" "1" "05 Mar 2020" "hub version 2.14.2" "hub manual"
.nh
.ad l
.SH "NAME"
hub\-create \- Create a new repository on GitHub and add a git remote for it.
.SH "SYNOPSIS"
.P
\fB\fChub create\fR [\-poc] [\-d \fIDESCRIPTION\fP] [\-h \fIHOMEPAGE\fP] [[\fIORGANIZATION\fP/]\fINAME\fP]
.SH "OPTIONS"
.PP
\-p, \-\-private
.RS 4
Create a private repository.
.RE
.PP
\-d, \-\-description \fIDESCRIPTION\fP
.RS 4
A short description of the GitHub repository.
.RE
.PP
\-h, \-\-homepage \fIHOMEPAGE\fP
.RS 4
A URL with more information about the repository. Use this, for example, if
your project has an external website.
.RE
.PP
\-\-remote\-name \fIREMOTE\fP
.RS 4
Set the name for the new git remote (default: "origin").
.RE
.PP
\-o, \-\-browse
.RS 4
Open the new repository in a web browser.
.RE
.PP
\-c, \-\-copy
.RS 4
Put the URL of the new repository to clipboard instead of printing it.
.RE
.PP
[\fIORGANIZATION\fP/]\fINAME\fP
.RS 4
The name for the repository on GitHub (default: name of the current working
directory).
.sp
Optionally, create the repository within \fIORGANIZATION\fP.
.RE
.br
.SH "EXAMPLES"
.PP
.RS 4
.nf
$ hub create
[ repo created on GitHub ]
> git remote add \-f origin git@github.com:USER/REPO.git

$ hub create sinatra/recipes
[ repo created in GitHub organization ]
> git remote add \-f origin git@github.com:sinatra/recipes.git
.fi
.RE
.SH "SEE ALSO"
.P
hub\-init(1), hub(1)

