.TH "hub-sync" "1" "05 Mar 2020" "hub version 2.14.2" "hub manual"
.nh
.ad l
.SH "NAME"
hub\-sync \- Fetch git objects from upstream and update local branches.
.SH "SYNOPSIS"
.P
\fB\fChub sync\fR [\-\-color]
.IP \(bu 2.3
If the local branch is outdated, fast\-forward it;
.sp -1
.IP \(bu 2.3
If the local branch contains unpushed work, warn about it;
.sp -1
.IP \(bu 2.3
If the branch seems merged and its upstream branch was deleted, delete it.
.br
.P
If a local branch does not have any upstream configuration, but has a
same\-named branch on the remote, treat that as its upstream branch.
.SH "OPTIONS"
.PP
\-\-color[=\fIWHEN\fP]
.RS 4
Enable colored output even if stdout is not a terminal. \fIWHEN\fP can be one
of "always" (default for \fB\fC\-\-color\fR), "never", or "auto" (default).
.RE
.br
.SH "SEE ALSO"
.P
hub(1), git\-fetch(1)

