.TH "hub-help" "1" "05 Mar 2020" "hub version 2.14.2" "hub manual"
.nh
.ad l
.SH "NAME"
hub\-help \- Show the help page for a command.
.SH "SYNOPSIS"
.P
\fB\fChub help\fR hub
.br
\fB\fChub help\fR \fICOMMAND\fP
.br
\fB\fChub help\fR hub\-\fICOMMAND\fP [\-\-plain\-text]
.SH "OPTIONS"
.PP
hub\-\fICOMMAND\fP
.RS 4
Use this format to view help for hub extensions to an existing git command.
.RE
.PP
\-\-plain\-text
.RS 4
Skip man page lookup mechanism and display raw help text.
.RE
.br
.SH "SEE ALSO"
.P
hub(1), git\-help(1)

