.TH "hub-browse" "1" "05 Mar 2020" "hub version 2.14.2" "hub manual"
.nh
.ad l
.SH "NAME"
hub\-browse \- Open a GitHub repository in a web browser.
.SH "SYNOPSIS"
.P
\fB\fChub browse\fR [\-uc] [[\fIUSER\fP/]\fIREPOSITORY\fP|\-\-] [\fISUBPAGE\fP]
.SH "OPTIONS"
.PP
\-u, \-\-url
.RS 4
Print the URL instead of opening it.
.RE
.PP
\-c, \-\-copy
.RS 4
Put the URL in clipboard instead of opening it.
.RE
.PP
[\fIUSER\fP/]\fIREPOSITORY\fP
.RS 4
Defaults to repository in the current working directory.
.RE
.PP
\fISUBPAGE\fP
.RS 4
One of "wiki", "commits", "issues", or other (default: "tree").
.RE
.br
.SH "EXAMPLES"
.PP
.RS 4
.nf
$ hub browse
> open https://github.com/REPO

$ hub browse \-\- issues
> open https://github.com/REPO/issues

$ hub browse jingweno/gh
> open https://github.com/jingweno/gh

$ hub browse gh wiki
> open https://github.com/USER/gh/wiki
.fi
.RE
.SH "SEE ALSO"
.P
hub\-compare(1), hub(1)

